-- RAM Informatica schema on independent Supabase project

create or replace function public.ram_is_admin()
returns boolean
language sql
stable
security invoker
set search_path = public
as $$
  select coalesce(
    (auth.jwt() -> 'app_metadata' ->> 'ram_role') = 'admin',
    false
  );
$$;

revoke all on function public.ram_is_admin() from public;
grant execute on function public.ram_is_admin() to anon, authenticated;

create or replace function public.ram_ensure_brand(p_name text)
returns public.ram_brands
language plpgsql
security definer
set search_path = public
as $$
declare
  v_name text := nullif(trim(p_name), '');
  v_row public.ram_brands;
begin
  if v_name is null then
    raise exception 'El nombre de la marca es obligatorio';
  end if;
  if not public.ram_is_admin() then
    raise exception 'No autorizado';
  end if;

  select * into v_row
  from public.ram_brands
  where lower(name) = lower(v_name)
  limit 1;

  if found then
    if v_row.active is distinct from true then
      update public.ram_brands
      set active = true, updated_at = now()
      where id = v_row.id
      returning * into v_row;
    end if;
    return v_row;
  end if;

  insert into public.ram_brands (name)
  values (v_name)
  on conflict (name) do update set active = true, updated_at = now()
  returning * into v_row;

  return v_row;
end;
$$;

revoke all on function public.ram_ensure_brand(text) from public;
grant execute on function public.ram_ensure_brand(text) to authenticated;

create table if not exists public.ram_products (
  id bigint generated by default as identity primary key,
  name text not null,
  brand text not null,
  category text not null,
  price numeric(12,0) not null check (price >= 0),
  old_price numeric(12,0) check (old_price is null or old_price >= 0),
  stock integer not null default 0 check (stock >= 0),
  rating numeric(3,1) not null default 4.5 check (rating >= 0 and rating <= 5),
  reviews integer not null default 0 check (reviews >= 0),
  installments text not null default '',
  description text not null default '',
  tags text[] not null default '{}',
  colors text[] not null default '{}',
  ram text not null default '',
  storage text not null default '',
  image_url text,
  subcategory text not null default '',
  provider text not null default '',
  cost_price numeric(12,2),
  active boolean not null default true,
  featured boolean not null default false,
  image_urls text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ram_providers (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  contact text not null default '',
  email text not null default '',
  phone text not null default '',
  address text not null default '',
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ram_brands (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  active boolean not null default true,
  logo_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ram_brands_name_unique unique (name)
);

create table if not exists public.ram_categories (
  id text primary key,
  name text not null,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ram_store_config (
  id integer primary key default 1 check (id = 1),
  store_name text not null default 'RAM Informatica',
  tagline text not null default '',
  support_email text not null default '',
  support_phone text not null default '',
  currency text not null default 'USD' check (currency in ('ARS','USD')),
  free_shipping_from numeric(12,0) not null default 0,
  shipping_cost numeric(12,0) not null default 0,
  installments_enabled boolean not null default true,
  max_installments integer not null default 12,
  announcement text not null default '',
  maintenance_enabled boolean not null default false,
  maintenance_title text not null default 'Estamos actualizando la pagina para una mejor experiencia.',
  maintenance_message text not null default 'Disculpe las molestias.',
  updated_at timestamptz not null default now()
);

-- Migración para bases ya creadas
alter table public.ram_store_config
  add column if not exists maintenance_enabled boolean not null default false,
  add column if not exists maintenance_title text not null default 'Estamos actualizando la pagina para una mejor experiencia.',
  add column if not exists maintenance_message text not null default 'Disculpe las molestias.';

create table if not exists public.ram_profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  name text not null default '',
  email text not null,
  phone text not null default '',
  dni text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ram_addresses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.ram_profiles (id) on delete cascade,
  label text not null default 'Casa',
  street text not null default '',
  city text not null default '',
  province text not null default '',
  zip text not null default '',
  phone text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.ram_orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  order_number text not null unique,
  status text not null default 'Procesando' check (status in ('Entregado','En camino','Procesando')),
  subtotal numeric(12,0) not null default 0,
  shipping numeric(12,0) not null default 0,
  total numeric(12,0) not null default 0,
  payment text not null default '',
  address text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.ram_order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.ram_orders (id) on delete cascade,
  product_id bigint references public.ram_products (id) on delete set null,
  name text not null,
  qty integer not null check (qty > 0),
  unit_price numeric(12,0) not null,
  line_total numeric(12,0) not null
);

create index if not exists ram_products_category_idx on public.ram_products (category);
create index if not exists ram_addresses_user_idx on public.ram_addresses (user_id);
create index if not exists ram_orders_user_idx on public.ram_orders (user_id);

alter table public.ram_products enable row level security;
alter table public.ram_providers enable row level security;
alter table public.ram_brands enable row level security;
alter table public.ram_categories enable row level security;
alter table public.ram_store_config enable row level security;
alter table public.ram_profiles enable row level security;
alter table public.ram_addresses enable row level security;
alter table public.ram_orders enable row level security;
alter table public.ram_order_items enable row level security;

drop policy if exists "ram_products_select" on public.ram_products;
create policy "ram_products_select" on public.ram_products
  for select to anon, authenticated
  using (active = true or public.ram_is_admin());

drop policy if exists "ram_products_admin_insert" on public.ram_products;
create policy "ram_products_admin_insert" on public.ram_products
  for insert to authenticated with check (public.ram_is_admin());

drop policy if exists "ram_products_admin_update" on public.ram_products;
create policy "ram_products_admin_update" on public.ram_products
  for update to authenticated
  using (public.ram_is_admin())
  with check (public.ram_is_admin());

drop policy if exists "ram_products_admin_delete" on public.ram_products;
create policy "ram_products_admin_delete" on public.ram_products
  for delete to authenticated using (public.ram_is_admin());

drop policy if exists "ram_providers_admin_select" on public.ram_providers;
create policy "ram_providers_admin_select" on public.ram_providers
  for select to authenticated using (public.ram_is_admin());

drop policy if exists "ram_providers_admin_insert" on public.ram_providers;
create policy "ram_providers_admin_insert" on public.ram_providers
  for insert to authenticated with check (public.ram_is_admin());

drop policy if exists "ram_providers_admin_update" on public.ram_providers;
create policy "ram_providers_admin_update" on public.ram_providers
  for update to authenticated
  using (public.ram_is_admin())
  with check (public.ram_is_admin());

drop policy if exists "ram_providers_admin_delete" on public.ram_providers;
create policy "ram_providers_admin_delete" on public.ram_providers
  for delete to authenticated using (public.ram_is_admin());

drop policy if exists "ram_brands_select" on public.ram_brands;
create policy "ram_brands_select" on public.ram_brands
  for select to anon, authenticated
  using (active = true or public.ram_is_admin());

drop policy if exists "ram_brands_admin_insert" on public.ram_brands;
create policy "ram_brands_admin_insert" on public.ram_brands
  for insert to authenticated with check (public.ram_is_admin());

drop policy if exists "ram_brands_admin_update" on public.ram_brands;
create policy "ram_brands_admin_update" on public.ram_brands
  for update to authenticated
  using (public.ram_is_admin())
  with check (public.ram_is_admin());

drop policy if exists "ram_brands_admin_delete" on public.ram_brands;
create policy "ram_brands_admin_delete" on public.ram_brands
  for delete to authenticated using (public.ram_is_admin());

drop policy if exists "ram_categories_select" on public.ram_categories;
create policy "ram_categories_select" on public.ram_categories
  for select to anon, authenticated
  using (active = true or public.ram_is_admin());

drop policy if exists "ram_categories_admin_insert" on public.ram_categories;
create policy "ram_categories_admin_insert" on public.ram_categories
  for insert to authenticated with check (public.ram_is_admin());

drop policy if exists "ram_categories_admin_update" on public.ram_categories;
create policy "ram_categories_admin_update" on public.ram_categories
  for update to authenticated
  using (public.ram_is_admin())
  with check (public.ram_is_admin());

drop policy if exists "ram_categories_admin_delete" on public.ram_categories;
create policy "ram_categories_admin_delete" on public.ram_categories
  for delete to authenticated using (public.ram_is_admin());

drop policy if exists "ram_config_select" on public.ram_store_config;
create policy "ram_config_select" on public.ram_store_config
  for select to anon, authenticated using (true);

drop policy if exists "ram_config_admin_update" on public.ram_store_config;
create policy "ram_config_admin_update" on public.ram_store_config
  for update to authenticated
  using (public.ram_is_admin())
  with check (public.ram_is_admin());

drop policy if exists "ram_config_admin_insert" on public.ram_store_config;
create policy "ram_config_admin_insert" on public.ram_store_config
  for insert to authenticated with check (public.ram_is_admin());

drop policy if exists "ram_profiles_select_own" on public.ram_profiles;
create policy "ram_profiles_select_own" on public.ram_profiles
  for select to authenticated using ((select auth.uid()) = id);

drop policy if exists "ram_profiles_insert_own" on public.ram_profiles;
create policy "ram_profiles_insert_own" on public.ram_profiles
  for insert to authenticated with check ((select auth.uid()) = id);

drop policy if exists "ram_profiles_update_own" on public.ram_profiles;
create policy "ram_profiles_update_own" on public.ram_profiles
  for update to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

drop policy if exists "ram_addresses_select_own" on public.ram_addresses;
create policy "ram_addresses_select_own" on public.ram_addresses
  for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "ram_addresses_insert_own" on public.ram_addresses;
create policy "ram_addresses_insert_own" on public.ram_addresses
  for insert to authenticated with check ((select auth.uid()) = user_id);

drop policy if exists "ram_addresses_update_own" on public.ram_addresses;
create policy "ram_addresses_update_own" on public.ram_addresses
  for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "ram_addresses_delete_own" on public.ram_addresses;
create policy "ram_addresses_delete_own" on public.ram_addresses
  for delete to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "ram_orders_select_own" on public.ram_orders;
create policy "ram_orders_select_own" on public.ram_orders
  for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "ram_orders_insert_own" on public.ram_orders;
create policy "ram_orders_insert_own" on public.ram_orders
  for insert to authenticated with check ((select auth.uid()) = user_id);

drop policy if exists "ram_order_items_select_own" on public.ram_order_items;
create policy "ram_order_items_select_own" on public.ram_order_items
  for select to authenticated
  using (
    exists (
      select 1 from public.ram_orders o
      where o.id = order_id and o.user_id = (select auth.uid())
    )
  );

drop policy if exists "ram_order_items_insert_own" on public.ram_order_items;
create policy "ram_order_items_insert_own" on public.ram_order_items
  for insert to authenticated
  with check (
    exists (
      select 1 from public.ram_orders o
      where o.id = order_id and o.user_id = (select auth.uid())
    )
  );

grant select on public.ram_products to anon, authenticated;
grant insert, update, delete on public.ram_products to authenticated;
grant select, insert, update, delete on public.ram_providers to authenticated;
grant select, insert, update, delete on public.ram_brands to anon, authenticated, service_role;
grant select, insert, update, delete on public.ram_categories to anon, authenticated, service_role;
grant select on public.ram_store_config to anon, authenticated;
grant insert, update on public.ram_store_config to authenticated;
grant select, insert, update on public.ram_profiles to authenticated;
grant select, insert, update, delete on public.ram_addresses to authenticated;
grant select, insert on public.ram_orders to authenticated;
grant select, insert on public.ram_order_items to authenticated;
grant usage, select on sequence public.ram_products_id_seq to authenticated;

create or replace function public.ram_handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.ram_profiles (id, name, email)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    coalesce(new.email, '')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists ram_on_auth_user_created on auth.users;
create trigger ram_on_auth_user_created
  after insert on auth.users
  for each row execute function public.ram_handle_new_user();

revoke all on function public.ram_handle_new_user() from public, anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'ram-media',
  'ram-media',
  true,
  5242880,
  array['image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "ram_media_public_read" on storage.objects;
create policy "ram_media_public_read"
  on storage.objects for select
  to anon, authenticated
  using (bucket_id = 'ram-media');

drop policy if exists "ram_media_admin_insert" on storage.objects;
create policy "ram_media_admin_insert"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'ram-media' and public.ram_is_admin());

drop policy if exists "ram_media_admin_update" on storage.objects;
create policy "ram_media_admin_update"
  on storage.objects for update
  to authenticated
  using (bucket_id = 'ram-media' and public.ram_is_admin())
  with check (bucket_id = 'ram-media' and public.ram_is_admin());

drop policy if exists "ram_media_admin_delete" on storage.objects;
create policy "ram_media_admin_delete"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'ram-media' and public.ram_is_admin());

-- Subcategorías (cada una pertenece a una categoría)
create table if not exists public.ram_subcategories (
  id uuid primary key default gen_random_uuid(),
  category_id text not null references public.ram_categories (id) on delete cascade on update cascade,
  name text not null,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ram_subcategories_unique unique (category_id, name)
);

alter table public.ram_subcategories enable row level security;

drop policy if exists "ram_subcategories_select" on public.ram_subcategories;
create policy "ram_subcategories_select" on public.ram_subcategories
  for select to anon, authenticated using (true);

drop policy if exists "ram_subcategories_admin_insert" on public.ram_subcategories;
create policy "ram_subcategories_admin_insert" on public.ram_subcategories
  for insert to authenticated with check (public.ram_is_admin());

drop policy if exists "ram_subcategories_admin_update" on public.ram_subcategories;
create policy "ram_subcategories_admin_update" on public.ram_subcategories
  for update to authenticated
  using (public.ram_is_admin())
  with check (public.ram_is_admin());

drop policy if exists "ram_subcategories_admin_delete" on public.ram_subcategories;
create policy "ram_subcategories_admin_delete" on public.ram_subcategories
  for delete to authenticated using (public.ram_is_admin());

grant select on public.ram_subcategories to anon, authenticated;
grant insert, update, delete on public.ram_subcategories to authenticated;

-- Carrito de usuarios logueados
create table if not exists public.ram_cart_items (
  user_id uuid not null references auth.users (id) on delete cascade,
  product_id bigint not null references public.ram_products (id) on delete cascade,
  qty integer not null default 1 check (qty > 0),
  updated_at timestamptz not null default now(),
  primary key (user_id, product_id)
);

alter table public.ram_cart_items enable row level security;

drop policy if exists "ram_cart_select_own" on public.ram_cart_items;
create policy "ram_cart_select_own" on public.ram_cart_items
  for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "ram_cart_insert_own" on public.ram_cart_items;
create policy "ram_cart_insert_own" on public.ram_cart_items
  for insert to authenticated with check ((select auth.uid()) = user_id);

drop policy if exists "ram_cart_update_own" on public.ram_cart_items;
create policy "ram_cart_update_own" on public.ram_cart_items
  for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "ram_cart_delete_own" on public.ram_cart_items;
create policy "ram_cart_delete_own" on public.ram_cart_items
  for delete to authenticated using ((select auth.uid()) = user_id);

grant select, insert, update, delete on public.ram_cart_items to authenticated;
